
-- 3: SETUP MIRRORING ENDPOINTS
-- Endpoints for Principal, Mirror, and Witness

-- On PRINCIPAL (S1)
CREATE ENDPOINT MirroringEndpoint
STATE = STARTED
AS TCP (LISTENER_PORT = 5022)
FOR DATABASE_MIRRORING (ROLE = PARTNER);

-- On MIRROR (S2)
CREATE ENDPOINT MirroringEndpoint
STATE = STARTED
AS TCP (LISTENER_PORT = 5023)
FOR DATABASE_MIRRORING (ROLE = PARTNER);

-- On WITNESS (S3)
CREATE ENDPOINT MirroringEndpoint
STATE = STARTED
AS TCP (LISTENER_PORT = 5024)
FOR DATABASE_MIRRORING (ROLE = WITNESS);
