-- STEP 4: START MIRRORING CONFIGURATION

-- Run on PRINCIPAL (S1)
ALTER DATABASE RetailDB 
SET PARTNER = 'TCP://SHRAVYA-REDDY\S2:5023';

-- Run on MIRROR (S2)
ALTER DATABASE RetailDB 
SET PARTNER = 'TCP://SHRAVYA-REDDY\S1:5022';

-- Run on PRINCIPAL (S1) to set Witness
ALTER DATABASE RetailDB 
SET WITNESS = 'TCP://SHRAVYA-REDDY\S3:5024';
